# Generated by Django 2.2.7 on 2019-11-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AlterField(
            model_name='dependent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='insurance.Member'),
        ),
    ]
