# Generated by Django 2.2.7 on 2019-11-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='member',
            field=models.ForeignKey(default='Plan Name', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.Member'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='member',
            field=models.ForeignKey(default='Family Member', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='insurance.Member'),
        ),
    ]
